accounts/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', views.loginview, name='login'),
    url(r'^logout/$', views.logoutview, name='logout'),
]

posts/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'posts'

urlpatterns = [
    url(r'^create/$', views.create, name='create'),
    url(r'^(?P<pk>[0-9]+)/upvote$', views.upvote, name='upvote'),
    url(r'^(?P<pk>[0-9]+)/downvote/$', views.downvote, name='downvote'),
    # url(r'^(?P<userid>[\d\w]+)/posts/$', views.user_posts, name='user_posts'),
    # url(r'^login/$', views.loginview, name='login'),
]

redditclone/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from posts import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'accounts/', include('accounts.urls')),
    url(r'posts/', include('posts.urls')),
    url(r'^$', views.home, name="home"),
    url(r'^(?P<username>[\w.@+-]+)/posts/$', views.user_posts, name='user_posts'),
]

accounts/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    url = models.TextField()
    pub_date = models.DateTimeField()
    author = models.ForeignKey(User)
    votes = models.IntegerField(default=1)

    def pub_date_pretty(self):
        return self.pub_date.strftime('%b %e %Y')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def signup(request):
    if request.method == 'POST':
        if validationComparePassword(request.POST['password'], request.POST['password-confirmation']):
            try:
                user = User.objects.get(username=request.POST['username'])
                return render(request, 'accounts/signup.html', { "message_error": "Username has already been taken."})
            except User.DoesNotExist:
                user = User.objects.create_user(username=request.POST['username'], email=request.POST['email'], password=request.POST['password'])
                login(request, user)
            #return render(request, 'accounts/signup.html', { "message_ok": "{} created".format(user)})
            return redirect('home')
        else:
            return render(request, 'accounts/signup.html', { "message_error": "Password do not match"})
    else:
        return render(request, 'accounts/signup.html')

def validationComparePassword(password1, password2):
    if password1.strip() == password2.strip():
        return True
    else:
        return False


# Create your views here.
def loginview(request):
    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST['next'])
            return redirect('home')
        return render(request, 'accounts/login.html', { "message_error": "Username or password does not match."})
    else:
        return render(request, 'accounts/login.html')


def logoutview(request):
    if request.method == 'POST':
        logout(request)
    return redirect('home')

posts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from .models import Post
from django.contrib.auth.models import User

# Create your views here.
@login_required
def create(request):
    if request.method == 'POST':
        if request.POST['title'] and request.POST['url']:
            post = Post()
            post.title = request.POST['title']
            if request.POST['url'].startswith('http://') or request.POST['url'].startswith('https://'):
                post.url = request.POST['url']
            else:
                post.url = 'http://'+ request.POST['url']
            post.pub_date = timezone.datetime.now()
            post.author = request.user
            post.save()
            return redirect('home')
        else:
            return render(request, "posts/create.html", { "message_error": "Title and URL are required fields"})

    else:
        return render(request, "posts/create.html")


def home(request):
    posts = Post.objects.order_by('-votes')
    return render(request, "posts/home.html", { 'posts': posts})

#    url(r'^(?P<pk>[0-9]+)/upvote$', views.upvote, name='upvote'),
#    url(r'^(?P<pk>[0-9]+)/downvote/$', views.downvote, name='downvote'),##
#

def upvote(request, pk):
    if request.method == 'POST':
        post = Post.objects.get(pk=pk)
        post.votes += 1
        post.save()
        return redirect('home')

def downvote(request, pk):
    if request.method == 'POST':
        post = Post.objects.get(pk=pk)
        post.votes -= 1
        post.save()
        return redirect('home')

# .all #filter(author.username = username) #.order_by('-votes')
def user_posts(request, username):
    try:
        user = User.objects.get(username=username)
        posts = Post.objects.filter(author=user) 
    except User.DoesNotExist:
        return render(request, 'posts/home.html', { "message_error": "User does not exist"})
    return render(request, "posts/user_posts.html", { 'posts': posts, 'user_post': username })

accounts/templates/accounts/login.html
{% extends 'base.html' %} {% block title %} Login Page{% endblock %} {% block content %} {% if message_ok %}
<div class="alert alert-primary" role="alert">
    {{ message_ok }}
</div>
{% endif %} {% if message_error %}
<div class="alert alert-danger" role="alert">
    {{ message_error }}
</div>
{% endif %}
<form class="form-horizontal" role="form" method="POST" action="{% url 'accounts:login' %}">
    {% csrf_token %} {% if request.GET.next %}
    <input type="hidden" name="next" value="{{ request.GET.next }}"> {% endif %}
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <h2>Login User</h2>
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3 field-label-responsive">
            <label for="username">Username</label>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                    <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-user"></i></div>
                    <input type="text" name="username" class="form-control" id="username" placeholder="Your_Username" required autofocus>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-control-feedback">
                <span class="text-danger align-middle">
                                <!-- Put name validation error messages here -->
                            </span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3 field-label-responsive">
            <label for="password">Password</label>
        </div>
        <div class="col-md-6">
            <div class="form-group has-danger">
                <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                    <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-key"></i></div>
                    <input type="password" name="password" class="form-control" id="password" placeholder="Password" required>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-control-feedback">
                <span class="text-danger align-middle">
                                <i class="fa fa-close"> Example Error Message</i>
                            </span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <button type="submit" class="btn btn-success"><i class="fa fa-user-plus"></i> Login</button>
        </div>
    </div>
</form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %} {% block title %} Signup Page{% endblock %} {% block content %} {% if message_ok %}
<div class="alert alert-primary" role="alert">
    {{ message_ok }}
</div>
{% endif %} {% if message_error %}
<div class="alert alert-danger" role="alert">
    {{ message_error }}
</div>
{% endif %}
<form class="form-horizontal" role="form" method="POST" action="{% url 'accounts:signup' %}">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <h2>Register New User</h2>
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3 field-label-responsive">
            <label for="username">Username</label>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                    <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-user"></i></div>
                    <input type="text" name="username" class="form-control" id="username" placeholder="Your_Username" required autofocus>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-control-feedback">
                <span class="text-danger align-middle">
                                <!-- Put name validation error messages here -->
                            </span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3 field-label-responsive">
            <label for="email">E-Mail Address</label>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                    <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-at"></i></div>
                    <input type="text" name="email" class="form-control" id="email" placeholder="you@example.com" required autofocus>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-control-feedback">
                <span class="text-danger align-middle">
                                <!-- Put e-mail validation error messages here -->
                            </span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3 field-label-responsive">
            <label for="password">Password</label>
        </div>
        <div class="col-md-6">
            <div class="form-group has-danger">
                <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                    <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-key"></i></div>
                    <input type="password" name="password" class="form-control" id="password" placeholder="Password" required>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-control-feedback">
                <span class="text-danger align-middle">
                                <i class="fa fa-close"> Example Error Message</i>
                            </span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3 field-label-responsive">
            <label for="password">Confirm Password</label>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                    <div class="input-group-addon" style="width: 2.6rem">
                        <i class="fa fa-repeat"></i>
                    </div>
                    <input type="password" name="password-confirmation" class="form-control" id="password-confirm" placeholder="Password" required>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <button type="submit" class="btn btn-success"><i class="fa fa-user-plus"></i> Register</button>
        </div>
    </div>
</form>
{% endblock %}

posts/templates/posts/create.html
{% extends 'base.html' %} {% block title %} Create Page{% endblock %} {% block content %} {% if message_ok %}
<div class="alert alert-primary" role="alert">
    {{ message_ok }}
</div>
{% endif %} {% if message_error %}
<div class="alert alert-danger" role="alert">
    {{ message_error }}
</div>
{% endif %}
<form class="form-horizontal" role="form" method="POST">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <h2>Create Post</h2>
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3 field-label-responsive">
            <label for="title">Title</label>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                    <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-user"></i></div>
                    <input type="text" name="title" class="form-control" id="title" placeholder="Title" required autofocus>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-control-feedback">
                <span class="text-danger align-middle">
                                <!-- Put name validation error messages here -->
                            </span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3 field-label-responsive">
            <label for="password">Url</label>
        </div>
        <div class="col-md-6">
            <div class="form-group has-danger">
                <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                    <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-key"></i></div>
                    <input type="input" name="url" class="form-control" id="url" placeholder="URL" required>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-control-feedback">
                <span class="text-danger align-middle">
                                <i class="fa fa-close"> Example Error Message</i>
                            </span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <button type="submit" class="btn btn-success"><i class="fa fa-user-plus"></i> Post</button>
        </div>
    </div>
</form>
{% endblock %}

posts/templates/posts/home.html
{% extends 'base.html' %} {% block title %} Home Page{% endblock %} {% block content %} {% if message_ok %}
<div class="alert alert-primary" role="alert">
    {{ message_ok }}
</div>
{% endif %} {% if message_error %}
<div class="alert alert-danger" role="alert">
    {{ message_error }}
</div>
{% endif %}
<h1>Home Page of nowhere</h1>
<a class="btn btn-primary" href="{% url 'posts:create' %}" role="button">New Post</a>
<br/>
<br/>
<br/> {% for post in posts.all %}
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-md-1">
                <div class="mx-auto text-center">
                    <form action="{% url 'posts:upvote' post.id %}" method="POST">{% csrf_token %}
                        <button type="submit" class="btn btn-success" value="UP">
                                        <i class="fas fa-arrow-up"></i></button>
                    </form>
                    {{ post.votes }}
                    <form action="{% url 'posts:downvote' post.id %}" method="POST">{% csrf_token %}
                        <button type="submit" class="btn btn-success" value="DOWN">
                                        <i class="fas fa-arrow-down"></i></button>
                    </form>
                </div>
            </div>
            <div class="col-md-11">
                <h5 class="card-title">
                    <a href="{{ post.url }}" target="_blank"> {{ post.title }}</a>
                </h5>
                <h6 class="card-subtitle mb-2 text-muted">{{ post.pub_date_pretty }} by
                    <a href="{% url 'user_posts' post.author.username %}">{{ post.author.username}} </a></h6>
            </div>
        </div>

    </div>
</div>
<br/>
<br/> {% endfor %} {% endblock %}

posts/templates/posts/user_posts.html
{% extends 'base.html' %} {% block title %} Home Page{% endblock %} {% block content %} {% if message_ok %}
<div class="alert alert-primary" role="alert">
    {{ message_ok }}
</div>
{% endif %} {% if message_error %}
<div class="alert alert-danger" role="alert">
    {{ message_error }}
</div>
{% endif %}
<h1>Home Page of nowhere</h1>
<h3>Posts from {{ user_post }}</h3>
<a class="btn btn-primary" href="{% url 'posts:create' %}" role="button">New Post</a>
<br/>
<br/>
<br/> {% for post in posts.all %}
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-md-1">
                <div class="mx-auto text-center">
                    <form action="{% url 'posts:upvote' post.id %}" method="POST">{% csrf_token %}
                        <button type="submit" class="btn btn-success" value="UP">
                                        <i class="fas fa-arrow-up"></i></button>
                    </form>
                    {{ post.votes }}
                    <form action="{% url 'posts:downvote' post.id %}" method="POST">{% csrf_token %}
                        <button type="submit" class="btn btn-success" value="DOWN">
                                        <i class="fas fa-arrow-down"></i></button>
                    </form>
                </div>
            </div>
            <div class="col-md-11">
                <h5 class="card-title">
                    <a href="{{ post.url }}" target="_blank"> {{ post.title }}</a>
                </h5>
                <h6 class="card-subtitle mb-2 text-muted">{{ post.pub_date_pretty }} by {{ post.author.username}}</h6>
            </div>
        </div>

    </div>
</div>
<br/>
<br/> {% endfor %} {% endblock %}

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">

    <style>
        .container {
            padding-top: 60px;
        }
        
        @media (max-width: 979px) {
            .container {
                padding-top: 0px;
            }
        }
    </style>

    <title>{% block title %} {% endblock %}</title>
</head>

<body>
    <!-- Image and text -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark navbar-right">
        <a class="navbar-brand" href="#">Reddit Clone</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                    </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active ">
                    <a class="nav-link " href="{% url 'home' %} ">Home <span class="sr-only ">(current)</span></a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link " href="# ">Features</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link " href="{% url 'home' %} ">About</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link " href="https://twitter.com/yeti_8848 ">Twitter</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item ">
                    <a class="nav-link " href="{% url 'user_posts' user.get_username %} ">My Posts</a>
                </li>
                {% endif %}

            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item ">
                    <span class="navbar-text">
                    Welcome, {{ user.get_username }}
                    </span>
                </li>
                <li class="nav-item ml">
                    <form action="{% url 'accounts:logout' %}" method="POST">{% csrf_token %}
                        <button type="submit" class="btn btn-link nav-link" value="logout">
                                        Logout</button>
                    </form>
                    {% else %}
                    <li class="nav-item ">
                        <a class="nav-link " href="{% url 'accounts:signup' %} ">Signup</a>
                    </li>
                    <li class="nav-item ml">
                        <a class="nav-link " href="{% url 'accounts:login' %} ">Login</a></li>
                    {% endif %}

            </ul>
        </div>
    </nav>
    <div class="container ">
        {% block content %} {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js " integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo " crossorigin="anonymous "></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js " integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49 " crossorigin="anonymous "></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js " integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T " crossorigin="anonymous "></script>
</body>

</html>